alter table public.broadcast_state
  alter column announcement type jsonb
  using case
    when announcement is null or btrim(announcement) = '' then null
    else jsonb_build_object('type','announcement','title',announcement)
  end;

alter table public.team_profiles drop constraint if exists team_profiles_panel_style_check;
alter table public.team_profiles add constraint team_profiles_panel_style_length_check
  check (char_length(panel_style) between 1 and 180000);

create policy commissioners_update_team_profiles
on public.team_profiles for update
to authenticated
using (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())))
with check (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())));

create or replace function public.update_team_profile(
  p_league_id text,
  p_roster_id integer,
  p_password text,
  p_team_name text,
  p_accent text,
  p_accent_2 text,
  p_panel_style text,
  p_motto text,
  p_badge text
) returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
  style_name text := split_part(coalesce(p_panel_style,''),'|',1);
begin
  if not coalesce((select t.password_hash = extensions.crypt(p_password, t.password_hash) from public.team_profiles t where t.league_id=p_league_id and t.roster_id=p_roster_id), false) then
    raise exception 'Invalid team password';
  end if;
  if p_accent !~ '^#[0-9A-Fa-f]{6}$' or p_accent_2 !~ '^#[0-9A-Fa-f]{6}$' then
    raise exception 'Invalid color';
  end if;
  if style_name not in ('broadcast','neon','championship','rivalry','carbon','grid','clean') or char_length(p_panel_style) > 180000 then
    raise exception 'Invalid panel style';
  end if;
  update public.team_profiles
     set team_name = left(trim(coalesce(p_team_name,'')), 36),
         accent = p_accent,
         accent_2 = p_accent_2,
         panel_style = p_panel_style,
         motto = left(trim(coalesce(p_motto,'')), 64),
         badge = left(trim(coalesce(p_badge,'')), 18),
         updated_at = now()
   where league_id=p_league_id and roster_id=p_roster_id;
  select jsonb_build_object(
    'league_id',t.league_id,'roster_id',t.roster_id,'display_name',t.display_name,'team_name',t.team_name,
    'accent',t.accent,'accent_2',t.accent_2,'panel_style',t.panel_style,'motto',t.motto,'badge',t.badge,'updated_at',t.updated_at
  ) into result from public.team_profiles t where t.league_id=p_league_id and t.roster_id=p_roster_id;
  update public.broadcast_state set updated_at = now() where league_id = p_league_id;
  return result;
end;
$$;

create or replace function public.clear_team_password(p_league_id text, p_roster_id integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null or not exists (select 1 from public.commissioners c where c.user_id = auth.uid()) then
    raise exception 'Commissioner access required';
  end if;
  update public.team_profiles set password_hash = null, updated_at = now()
   where league_id = p_league_id and roster_id = p_roster_id;
  if not found then raise exception 'Team not found'; end if;
  return true;
end;
$$;

grant execute on function public.clear_team_password(text, integer) to authenticated;

create table public.playlist_items (
  id bigint generated by default as identity primary key,
  league_id text not null references public.broadcast_state(league_id) on delete cascade,
  url text not null check (char_length(url) between 12 and 600 and (url ~ '^https://music[.]apple[.]com/' or url ~ '^https://open[.]spotify[.]com/')),
  requested_by text not null default 'Draft guest' check (char_length(requested_by) between 1 and 40),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.playlist_items enable row level security;
create policy public_read_playlist on public.playlist_items for select to anon, authenticated using (active = true);
create policy public_add_playlist on public.playlist_items for insert to anon, authenticated with check (active = true);
create policy commissioners_manage_playlist on public.playlist_items for all to authenticated
using (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())))
with check (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())));

grant select, insert on public.playlist_items to anon, authenticated;
grant usage, select on sequence public.playlist_items_id_seq to anon, authenticated;
