create table public.pick_requests (
  id bigint generated by default as identity primary key,
  league_id text not null references public.broadcast_state(league_id) on delete cascade,
  draft_id text not null check (draft_id ~ '^[0-9]{10,24}$'),
  pick_no integer not null check (pick_no between 1 and 1000),
  roster_id integer not null check (roster_id between 1 and 32),
  player_id text not null check (char_length(player_id) between 1 and 32),
  player_name text not null check (char_length(player_name) between 1 and 96),
  position text not null check (position in ('QB','RB','WR','TE','K','DEF')),
  nfl_team text not null default 'FA' check (char_length(nfl_team) between 1 and 4),
  status text not null default 'pending' check (status in ('pending','processing','submitted','confirmed','rejected','cancelled','failed','stale')),
  operator_note text check (operator_note is null or char_length(operator_note) <= 280),
  official_pick_no integer check (official_pick_no is null or official_pick_no between 1 and 1000),
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create unique index pick_requests_one_active_pick_idx
  on public.pick_requests (league_id, draft_id, pick_no)
  where status in ('pending','processing','submitted');
create index pick_requests_operator_queue_idx
  on public.pick_requests (league_id, status, requested_at desc);

alter table public.pick_requests enable row level security;
revoke all on table public.pick_requests from public, anon;
revoke all on sequence public.pick_requests_id_seq from public, anon, authenticated;

create policy commissioners_read_pick_requests
on public.pick_requests for select to authenticated
using (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())));

create policy commissioners_update_pick_requests
on public.pick_requests for update to authenticated
using (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())))
with check (exists (select 1 from public.commissioners c where c.user_id = (select auth.uid())));

grant select, update on public.pick_requests to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.pick_requests;
exception when duplicate_object then null;
end $$;
